### ISSUE TITLE
RunTimeException in IntentReceiver

### ISSUE THREAD

**Issue by Aracem** [Notificare/notificare-push-lib-android#4]
Hello

I receiving RuntimeExceptions in the **onReady()** method of my BaseIntentReceiver

This is my code
```java
@Override
    public void onReady() {
        // Enable this device for push notifications
        Notificare.shared().enableNotifications();

        Notificare.shared().enableLocationUpdates();
    }
```

And this is the error:

```java
java.lang.RuntimeException: Unable to start receiver me.upclose.aether.api.services.notifications.notificare.NotificareIntentReceiver: java.lang.RuntimeException: Please call this method only after applicationInfo is loaded, so after onReady event
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2580)
       at android.app.ActivityThread.access$1700(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Please call this method only after applicationInfo is loaded, so after onReady event
       at re.notifica.Notificare.enableNotifications(Notificare.java:1395)
       at me.upclose.aether.api.services.notifications.notificare.NotificareIntentReceiver.onReady(NotificareIntentReceiver.java:44)
       at re.notifica.push.gcm.BaseIntentReceiver.onReceive(BaseIntentReceiver.java:61)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2573)
       at android.app.ActivityThread.access$1700(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

This seems to happens when the application is closed and the device receive a notification

**Comment by silentjohnny** [comment]
@aracem,

This is something we noticed too since the update to Android 5.0 / 5.1. It seems to occur when the onReady intent is received after the process was killed, which seems to happen more aggressively in 5.0.

I think it would be best if we replace the RuntimeExceptions with log warnings, so at least they don't crash apps in places where they shouldn't crash, but you will still be able to see while developing.

I will release a 1.4.3 SDK version today, but until then, please surround the enableNotifications with a try / catch

As always, thanks for notifying!

**Comment by Aracem** [comment]
Thank you for your quick answer :) !!

**Comment by silentjohnny** [comment]
@aracem 

1.4.3 is released, also in https://github.com/Notificare/notificare-mvn-repo 

This release fixes crashes at app launch.

**Comment by Aracem** [comment]
@silentjohnny  Perfect! Thanks :dancer:
