### ISSUE TITLE
Crashes in NotificationContainerFragment.java  (NotificareCallback not safe)

### ISSUE THREAD

**Issue by nethergrim** [Notificare/notificare-push-lib-android#6]
Hi!

We have lot's of crashes with the same stacktrace:

> Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{1977a7 V.E...... R......D 0,0-1026,483} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:118)
       at android.app.Dialog.dismissDialog(Dialog.java:362)
       at android.app.Dialog.dismiss(Dialog.java:345)
       at re.notifica.ui.NotificationContainerFragment$1.onSuccess(NotificationContainerFragment.java:182)
       at re.notifica.ui.NotificationContainerFragment$1.onSuccess(NotificationContainerFragment.java:176)
       at re.notifica.action.App$1.onSuccess(App.java:53)
       at re.notifica.action.App$1.onSuccess(App.java:48)
       at re.notifica.Notificare$19.onCompleted(Notificare.java:3441)
       at re.notifica.api.Request$1.onPostExecute(Request.java:264)
       at re.notifica.api.Request$1.onPostExecute(Request.java:254)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

And I'm pretty sure it's a bug in Notificare SDK. Occured on 1.8.7, but I can see the same "unsafe" code in 1.9.1.

So I'd suggest to check if activity is not null inside of the NotificareCallback.

Thanks!

**Comment by nethergrim** [comment]
Also one more stacktrace from there:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.widget.Toast.makeText(Toast.java:531)
       at re.notifica.ui.NotificationContainerFragment$1.onSuccess(NotificationContainerFragment.java:183)
       at re.notifica.ui.NotificationContainerFragment$1.onSuccess(NotificationContainerFragment.java:176)
       at re.notifica.action.App$1.onSuccess(App.java:53)
       at re.notifica.action.App$1.onSuccess(App.java:48)
       at re.notifica.Notificare$19.onCompleted(Notificare.java:3441)
       at re.notifica.api.Request$1.onPostExecute(Request.java:264)
       at re.notifica.api.Request$1.onPostExecute(Request.java:254)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.access$500(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by nethergrim** [comment]
And the last one from there:

> Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{2651464b V.E..... R......D 0,0-684,322} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:386)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:312)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
       at android.app.Dialog.dismissDialog(Dialog.java:349)
       at android.app.Dialog.dismiss(Dialog.java:332)
       at re.notifica.ui.NotificationContainerFragment$1.onError(NotificationContainerFragment.java:199)
       at re.notifica.action.App$1.onError(App.java:59)
       at re.notifica.Notificare$19.onCompleted(Notificare.java:3437)
       at re.notifica.api.Request$1.onPostExecute(Request.java:264)
       at re.notifica.api.Request$1.onPostExecute(Request.java:254)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by nethergrim** [comment]
All three of them are related to the bug I mentioned in the first message. So when callback is called activity may be null, or dialog can be detached already, so additional checks need to be done there.

**Comment by nethergrim** [comment]
Just also wanted to mention that I'm from [MOBILE STRATEGY](http://www.mobilestrategy.nl), and we have a paid plan :)

**Comment by silentjohnny** [comment]
@nethergrim 

we don't see those crashes in apps, so to dig down a bit deeper: how did you setup your NotificationActivity? Are you opening it from the NotificationManager intent (intent filter in the manifest) or starting it from another activity? 

Just want to make sure we are looking at the actual cause.

**Comment by nethergrim** [comment]
@silentjohnny 

Here is the config for NotificationManager:

> <activity
            android:name="re.notifica.ui.NotificationActivity"
            android:parentActivityName=".activities.MainActivity"
            android:theme="@style/NotificareTheme">
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".activities.MainActivity" />
        </activity>

**Comment by nethergrim** [comment]
Basically, issue is simple.
Web request fired inside of NotificationContainerFragment, with a callback. And in callback link to Activity is used. But there are no checks to ensure that activity is still running, active, and exist.
Generally it can be fixed with few simple checks.

**Comment by silentjohnny** [comment]
SDK 1.9.7 was released yesterday
